TRUNCATE TABLE account CASCADE;
TRUNCATE TABLE product CASCADE;
TRUNCATE TABLE agreement CASCADE;
-- TRUNCATE TABLE operation_type CASCADE;
TRUNCATE TABLE operation CASCADE;
TRUNCATE TABLE card_product CASCADE;
TRUNCATE TABLE card CASCADE;